# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8989
#  port: 8990
# connection-timeout: 25000ms
  servlet:
    context-path: /anlian_sys

http:
  port: 8082
    
management:
  server:
    port: 8080
    ssl:
      enabled: false


spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
      enabled: true
#  redis:
#    open: true  # 是否开启redis缓存  true开启   false关闭
#    database: 0
#    host: 127.0.0.1 #测试服务器redis
#    host: 192.168.0.203 #测试服务器redis
#    host: 192.168.0.215 #测试服务器redis
#    host: 47.111.249.220 #线上服务器redis
#    port: 6379
#    password: aJqNteYZ9D   # 密码（默认为空）测试redis密码
#    password: ldlJRxthNeabA3Fd   # 密码（默认为空） 线上redis密码f
#    timeout: 6000ms  # 连接超时时长（毫秒）
#    jedis:
#      pool:
#        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
#        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-idle: 10      # 连接池中的最大空闲连接
#        min-idle: 5       # 连接池中的最小空闲连接
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**
  resources: 
    add-mappings: false
  jmx:
    #enabled: true
    default-domain: icas3

  #邮箱配置
#  mail:
    #smtp服务主机  qq邮箱则为smtp.qq.com
#    host: smtp.exmail.qq.com
    #服务协议
#    protocol: smtp
    # 编码集
#    default-encoding: UTF-8
    #发送邮件的账户
#    username: noreply@anliantest.com
#    username: service2@anliantest.com
    #授权码
#    password: kRTYWpwCeLRnPJrp  Xvf5Ha6KrcDjHRYd  g3enUK2iUsWvDrrT
#    password: g3enUK2iUsWvDrrT
#    test-connection: true
#    port: 465
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
#          socketFactory:
#            port: 465
#            class: javax.net.ssl.SSLSocketFactory
#            fallback: false
#      anlian: http://47.111.249.220:81

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: may.yuntian.modules.*.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      #驼峰下划线转换
      column-underline: true
      #逻辑删除配置
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

#minio:
#  #线上
#  accessKey: admin
#  secretKey: 8hx71XplD5Fe
#  bucketName: anlian-java
#  endpoint: http://39.185.236.201:31951
  #测试
#  accessKey: anlian
#  secretKey: 8hx71XplD5Fe
#  bucketName: anlian-java
#  endpoint: http://192.168.0.203:9010

yuntian:
  redis:
    open: true
  shiro:
    redis: true
  # APP模块，是通过jwt认证的，如果要使用APP模块，则需要修改【加密秘钥】
  jwt:
    # 加密秘钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # token有效时长，7天，单位秒
    expire: 604800
    header: token

# 项目相关配置
anlian:
  # 文件上传、下载的存储路径
  path:
    file-path: /Users/mayong/develop/anlian/
    prefix:
      #工艺流程图路径
      craftProcess: craftProcess/
      #设备布局测点布置图路径
      equipment: equipment/
      download: download/
      upload: upload/
    staticPath: E:/webapps/
  sys:
    # 系统认证密钥
    secretKey: 317908D630194FDEAB8A9F8782B4B61C035C59E7C65B4087B1F9331C0A3951B084535215C71B4491836A0D4F294923A08E7F31AF92E44AD6BDAF1435414DE1CB
# 第三方业务接口
interface:
  # 汝成科技-万达仓库
  WD:
    # 测试地址前缀
    url: http://124.70.146.112:8090/api/zyws
    #    # 技术服务机构名称
    orgName: 浙江安联检测技术服务有限公司
    #    # 技术服务机构统一社会信用代码
    orgCode: 913301085714775903
    # 技术服务机构密钥（由对方生成并提供）
    orgKey: b6b72a65073a5ad7a4cf77ee3241928a
    # 同步成功的第三方技术服务机构id
    orgId: 8319810039305273344
    #    # 技术服务机构法人名称 and 检测报告签发人
    legalName: 王勇
#    # 技术服务机构法人电话
#    legalPhone: 13588028384
#    # 技术服务机构注册行政区划
#    registerArea: 浙江省杭州市滨江区浦沿街道
#    # 技术服务机构注册行政区划编码
#    registerAreaCode: 330108003000
#    # 技术服务机构注册地址详情
#    registerAddress: 浙江省杭州市滨江区浦沿街道东冠路611号8幢5层

  # 顺丰快递
  SF:
    # 顾客编码
    clientCode: ALJCJZAF2LL8
#    # 沙箱月结卡号
#    monthlyCard: 7551234567
#    # 沙箱校验码
#    checkWord: nREfgsln7qDHztmlZRlA2lOG8OQJISlx
#    # 沙箱环境地址
#    callUrl: https://sfapi-sbox.sf-express.com/std/service
    # 生产月结卡号
    monthlyCard: 5717080125
    # 生产校验码
    checkWord: K7LVnhcIQvVGP4aPNNRWa1pG806urIzS
    # 生产环境地址
    callUrl: https://bspgw.sf-express.com/std/service