spring:
  data:
    mongodb:
      uri: mongodb://anlian:lNe2Ij6*V.~MYvW#@192.168.0.203:27027/anlian?mechanism=SCRAM-SHA-1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      first:  #数据源2 阿里云数据库配置
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.0.203:3306/anlian_v2?useSSL=false&serverTimezone=GMT%2B8&
        username: anlian
        password: AwQWNjfF)Z0d.RM~

        #数据源4 本地数据库配置
        #        url: jdbc:mysql://192.168.0.229:3306/anlian?useSSL=false&serverTimezone=GMT%2B8&
        #        username: root
        #        password: root

        # 本地测试-线上47-anlian_v2
      #        url: jdbc:mysql://localhost:3308/anlian_v2_localtest?useSSL=false&serverTimezone=GMT%2B8&
      #        username: root
      #        password: 123456

      second:  #数据源2 阿里云数据库配置
        enabled: true
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://47.114.191.58:3306/anliantest_com?useSSL=false&serverTimezone=GMT%2B8&
        username: anliantest_com
        password: SChweBAzG5mpGB35
      initial-size: 5
      max-active: 30
      min-idle: 3
      max-wait: 120000
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 120000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
  # redis配置
  redis:
    open: true  # 是否开启redis缓存  true开启   false关闭
    database: 0
    host: 192.168.0.203
    port: 6379
    password: aJqNteYZ9D   # 密码（默认为空）测试redis密码
    timeout: 6000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  #邮箱配置
  mail:
    #smtp服务主机  qq邮箱则为smtp.qq.com
    host: smtp.exmail.qq.com
    #服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    #    username: noreply@anliantest.com
    username: service2@anliantest.com
    #授权码
    #    password: kRTYWpwCeLRnPJrp  Xvf5Ha6KrcDjHRYd  g3enUK2iUsWvDrrT
    password: g3enUK2iUsWvDrrT
    test-connection: true
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
      anlian: http://192.160.0.203:81
minio:
  accessKey: anlian
  secretKey: 8hx71XplD5Fe
  bucketName: anlian-java
  endpoint: http://192.168.0.203:9010
apiPath:
  pythonPjPdfApi: http://192.168.0.203:86/proxyAnlianPjPython/
  pythonZjPdfApi: http://192.168.0.203:84/proxyAnlianZjPython/