spring:
  data:
    mongodb:
      uri: mongodb://anlian:1GaCKf1oUcQYb3km@mongodb-ee7t8e.business-test:27017/anlian?mechanism=SCRAM-SHA-1
#      uri: mongodb://anlian:1GaCKf1oUcQYb3km@47.111.249.220:27017/anlian?mechanism=SCRAM-SHA-1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      first:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://mysql-h6slju-headless.business-test:3306/anlian_v2?useSSL=false&serverTimezone=GMT%2B8&
        username: root
        password: eQ8MMF5M4c
#        url: jdbc:mysql://47.111.249.220:3306/anlian_v2?useSSL=false&serverTimezone=GMT%2B8&
#        username: anlian
#        password: E&ZC^C9kyH4XP!-0
      second:  #数据源2 阿里云数据库配置
        # 从数据源开关/默认关闭
        enabled: true
        # 数据源2 本地数据库配置
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://47.114.191.58:3306/anliantest_com?useSSL=false&serverTimezone=GMT%2B8&
        username: anliantest_com
        password: SChweBAzG5mpGB35
      initial-size: 5
      max-active: 30
      min-idle: 3
      max-wait: 120000  #60000
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 120000 #60000
      min-evictable-idle-time-millis: 300000
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

  redis:
    open: true  # 是否开启redis缓存  true开启   false关闭
    database: 0
    host: redis-mz28kr-headless.business-test
#    host: 47.111.249.220
    port: 6379
    password: ldlJRxthNeabA3Fd
    timeout: 6000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  #邮箱配置
  mail:
    #smtp服务主机  qq邮箱则为smtp.qq.com
    host: smtp.exmail.qq.com
    #服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    #    username: noreply@anliantest.com
    username: service2@anliantest.com
    #授权码
    #    password: kRTYWpwCeLRnPJrp  Xvf5Ha6KrcDjHRYd  g3enUK2iUsWvDrrT
    password: g3enUK2iUsWvDrrT
    test-connection: true
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
      anlian: http://39.185.236.201:81
#      anlian: http://47.111.249.220:81
#线上
minio:
  accessKey: admin
  secretKey: 8hx71XplD5Fe
  bucketName: anlian-java
  endpoint: http://minio-skqsqb.business-test:9000
#  accessKey: admin
#  secretKey: 8hx71XplD5Fe
#  bucketName: anlian-java
#  endpoint: http://39.185.236.201:31951
apiPath:
#  pythonPjPdfApi: http://47.111.249.220:86/proxyAnlianPjPython/
  pythonPjPdfApi: http://pj-gunicorn-svc.business-test:9890/
#  pythonZjPdfApi: http://47.111.249.220:84/proxyAnlianZjPython/
  pythonZjPdfApi: http://zj-gunicorn-svc.business-test:9890/


